name: Check PR
on:
  workflow_dispatch:
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.5.0
      - uses: cloudposse/github-action-pre-commit@v3.0.0
